var result  = {
    "profile": {
        "info": {
            "profile_id": "farhan",
            "full_name": "Farhan Zaman",
            "first_name": "Farhan",
            "last_name": "Zaman",
            "nick_name": "Arnob",
            "designations": "Software Engineer",
            "intro_text": "A tech enthusiast, always ready for new challenges and\r\n            quick learner. To know more about my works and interests check out my details.",
            "intro_image_url": "view\/static\/intro.png",
            "resume_url": "view\/static\/resume.pdf",
            "expertise_preference_details": "Drawing upon a wide range of skills and technical proficiencies, I excel in\r\n                problem solving, critical thinking, and effective teamwork. My expertise extends to encompass business\r\n                communication, interpersonal skills, and adaptability in dynamic environments. Additionally, I possess\r\n                leadership qualities, polished presentation skills, and a keen sense of creativity. Proficient in Java,\r\n                PHP, JavaScript, Python, and other languages, I am well-versed in leveraging frameworks such as\r\n                SpringBoot, ReactJS, NodeJS, and more. With a self-motivated and organized approach, I consistently\r\n                demonstrate exceptional time management and the ability to excel in various projects.",
            "website_base_url": "https:\/\/farhanzaman.dev",
            "website_domain_name": "farhanzaman.dev",
            "contact_preference_details": "For any professional inquiries or opportunities, or if you simply want to get in touch, please feel free to contact me using the provided contact details. I am readily available to discuss potential alliance, projects, or career prospects. Your interest is greatly appreciated, and I look forward to the possibility of working together.",
            "address": "35, LAKECIRCUS, KALABAGAN, Dhaka, Bangladesh -1205",
            "phone": "(+880) 1521581368",
            "secondary_phone": "9876543210",
            "email": "fz.arnob@gmail.com",
            "alternative_email": "farhanzamanarnob@gmail.com",
            "facebook_url": "https:\/\/www.facebook.com\/farhanzamanarnob\/",
            "github_url": "https:\/\/github.com\/FzArnob",
            "linkedin_url": "https:\/\/www.linkedin.com\/in\/md-farhan-zaman\/",
            "whatsapp_url": "https:\/\/wa.me\/8801521581368",
            "created_date": "2023-06-11 15:29:12",
            "updated_date": "2023-06-26 00:00:59",
            "delete_flag": "0"
        },
        "educations": [
            {
                "education_id": "1",
                "institute_name": "BRAC University",
                "institute_std": null,
                "institute_url": "https:\/\/www.bracu.ac.bd\/",
                "start_date": "2022-05-29",
                "end_date": null,
                "is_present": "1",
                "subject": "Studies MBA - Master in Business Administration",
                "activity": "Specialization in Operation Management",
                "created_date": "2023-06-26 01:02:30",
                "updated_date": "2023-06-26 01:02:30",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "education_id": "2",
                "institute_name": "BRAC University",
                "institute_std": null,
                "institute_url": "https:\/\/www.bracu.ac.bd\/",
                "start_date": null,
                "end_date": "2022",
                "is_present": "0",
                "subject": "Studied Bachelor of Science in Computer Science and Engineering (CSE)",
                "activity": "Former Senior Executive at BRAC University Community Service Club (BUCSC)",
                "created_date": "2023-06-26 01:02:30",
                "updated_date": "2023-06-26 01:02:30",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "education_id": "3",
                "institute_name": "Dhaka College",
                "institute_std": null,
                "institute_url": "https:\/\/dhakacollege.edu.bd\/",
                "start_date": null,
                "end_date": "2016",
                "is_present": "0",
                "subject": "Studied Science: High School (12th Grade)",
                "activity": "Former General Secretary at Dhaka College Science Club (DCSC)",
                "created_date": "2023-06-26 01:02:30",
                "updated_date": "2023-06-26 01:02:30",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "education_id": "4",
                "institute_name": "Ideal School & College",
                "institute_std": null,
                "institute_url": "https:\/\/iscm.edu.bd\/",
                "start_date": null,
                "end_date": "2014",
                "is_present": "0",
                "subject": "Studied Science: Secondary School (10th Grade)",
                "activity": "Received JSC Government Scholarship 2011",
                "created_date": "2023-06-26 01:02:30",
                "updated_date": "2023-06-26 01:02:30",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "experiences": [
            {
                "experience_id": "1",
                "institute_name": "BJIT Group",
                "institute_std": null,
                "institute_url": "https:\/\/bjitgroup.com\/",
                "start_date": "2022-03-29",
                "end_date": null,
                "is_present": "1",
                "position": "Software Engineer",
                "project_details": "Core Backend Engineer",
                "project_text_1": "Pocketalk",
                "project_text_2": null,
                "project_text_3": null,
                "project_url_1": "https:\/\/www.pocketalk.com\/",
                "project_url_2": null,
                "project_url_3": null,
                "created_date": "2023-06-26 01:23:40",
                "updated_date": "2023-06-26 01:23:40",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "experience_id": "2",
                "institute_name": "Doodle Inc.",
                "institute_std": null,
                "institute_url": "https:\/\/www.thedoodleinc.com\/",
                "start_date": "2021-09-01",
                "end_date": "2022-02-28",
                "is_present": "0",
                "position": "Former Full Stack Software Engineer and Developer",
                "project_details": "Serverless System Architect",
                "project_text_1": "Tribel",
                "project_text_2": null,
                "project_text_3": null,
                "project_url_1": "https:\/\/www.tribel.com\/",
                "project_url_2": null,
                "project_url_3": null,
                "created_date": "2023-06-26 01:23:40",
                "updated_date": "2023-06-26 01:23:40",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "experience_id": "3",
                "institute_name": "Forecast",
                "institute_std": null,
                "institute_url": "https:\/\/www.facebook.com\/forecast.org\/",
                "start_date": "2018-04-15",
                "end_date": "2021-03-31",
                "is_present": "0",
                "position": "Former Lecturer",
                "project_details": "Higher Mathematics Instructor and Physics Coordinator",
                "project_text_1": null,
                "project_text_2": null,
                "project_text_3": null,
                "project_url_1": null,
                "project_url_2": null,
                "project_url_3": null,
                "created_date": "2023-06-26 01:23:40",
                "updated_date": "2023-06-26 01:23:40",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "expertises": [
            {
                "expertise_id": "1",
                "name": "HTML",
                "description": "Hypertext Markup Language",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "2",
                "name": "CSS",
                "description": "Cascading Style Sheets",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "3",
                "name": "JavaScript",
                "description": "Client-side scripting language",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "4",
                "name": "TypeScript",
                "description": "Typed superset of JavaScript",
                "duration": "60",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "5",
                "name": "Python",
                "description": "General-purpose programming language",
                "duration": "120",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "6",
                "name": "Java",
                "description": "Object-oriented programming language",
                "duration": "120",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "7",
                "name": "C++",
                "description": "General-purpose programming language",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "8",
                "name": "PHP",
                "description": "Server-side scripting language",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "9",
                "name": "SpringBoot",
                "description": "Java-based framework",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "10",
                "name": "ReactJS",
                "description": "JavaScript library for building UIs",
                "duration": "120",
                "level": "Advanced",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "11",
                "name": "MongoDB",
                "description": "NoSQL database program",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "12",
                "name": "NodeJS",
                "description": "JavaScript runtime environment",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "13",
                "name": "MySQL",
                "description": "Relational database management system",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "14",
                "name": "NoSQL",
                "description": "Database management system",
                "duration": "60",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "15",
                "name": "GraphQL",
                "description": "Query language for APIs",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "16",
                "name": "Selenium",
                "description": "Web browser automation tool",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "17",
                "name": "OOD",
                "description": "Object-oriented design",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "18",
                "name": "Redux",
                "description": "Predictable state container for JavaScript apps",
                "duration": "60",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "19",
                "name": "jQuery",
                "description": "Fast, small, and feature-rich JavaScript library",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "20",
                "name": "Photoshop",
                "description": "Raster graphics editor",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "21",
                "name": "Illustrator",
                "description": "Vector graphics editor",
                "duration": "90",
                "level": "Intermediate",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "22",
                "name": "Excel",
                "description": "Spreadsheet program",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "expertise_id": "23",
                "name": "PowerPoint",
                "description": "Presentation software",
                "duration": "60",
                "level": "Beginner",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "skills": [
            {
                "skill_id": "1",
                "name": "Problem Solving",
                "description": "Proficient in identifying and analyzing problems, and developing effective solutions.",
                "duration": "12",
                "percentage": "92",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "2",
                "name": "Critical thinking",
                "description": "Skilled at evaluating situations objectively and making reasoned judgments.",
                "duration": "8",
                "percentage": "80",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "3",
                "name": "Teamwork",
                "description": "Demonstrates strong collaboration and cooperation skills within a team setting.",
                "duration": "24",
                "percentage": "78",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "4",
                "name": "Leadership",
                "description": "Experienced in leading teams and guiding them towards achieving common goals.",
                "duration": "36",
                "percentage": "82",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "5",
                "name": "Interpersonal skills",
                "description": "Capable of building and maintaining positive relationships with others.",
                "duration": "18",
                "percentage": "75",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "6",
                "name": "Adaptability",
                "description": "Quickly adapts to new environments and can adjust strategies as needed.",
                "duration": "10",
                "percentage": "68",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "7",
                "name": "Business Communication",
                "description": "Effective communication skills for conveying information in a professional setting.",
                "duration": "16",
                "percentage": "85",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "8",
                "name": "Presentation skills",
                "description": "Skilled in delivering engaging and informative presentations to diverse audiences.",
                "duration": "14",
                "percentage": "88",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "9",
                "name": "Creativity",
                "description": "Displays innovative thinking and generates unique ideas for problem-solving.",
                "duration": "20",
                "percentage": "72",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "10",
                "name": "Self-motivated",
                "description": "Highly self-driven and takes initiative to accomplish tasks and achieve goals.",
                "duration": "30",
                "percentage": "78",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "11",
                "name": "Organizational skills",
                "description": "Efficiently manages time, resources, and tasks to meet objectives.",
                "duration": "12",
                "percentage": "65",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "skill_id": "12",
                "name": "Time management",
                "description": "Adept at prioritizing tasks and meeting deadlines effectively.",
                "duration": "22",
                "percentage": "82",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "achievements": [
            {
                "achievement_id": "1",
                "name": "Java Selenium",
                "description": "TestDome is a provider of high-quality, online skills tests that use work-sample testing methodology to screen knowledge workers. Candidates are evaluated through small samples of actual work that show how they solve problems in the real world.",
                "certification_date": "2022-02-21",
                "certification_url": "https:\/\/www.testdome.com\/certificates\/550c055c41aa429a88d9ea52f93f2228",
                "certification_logo": "view\/static\/svg\/selenium.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "2",
                "name": "IELTS",
                "description": "IELTS Score: 7.0 - Strong proficiency in English language demonstrated.",
                "certification_date": "2022-02-21",
                "certification_url": "https:\/\/www.britishcouncil.org.bd\/en\/exam\/ielts",
                "certification_logo": "view\/static\/svg\/ielts.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "3",
                "name": "BeeCrowd: Competitive Programming",
                "description": "BeeCrowd is a global community of developers committed to keep evolving as students and professionals.",
                "certification_date": "2023-06-25",
                "certification_url": "https:\/\/www.beecrowd.com.br\/judge\/en\/profile\/151481",
                "certification_logo": "view\/static\/svg\/beecrowd.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "4",
                "name": "Python",
                "description": "Python (Basic): It covers topics like Scalar Types, Operators and Control Flow, Strings, Collections and Iteration, Modularity, Objects and Types and Classes",
                "certification_date": "2021-12-02",
                "certification_url": "https:\/\/www.hackerrank.com\/certificates\/3859fe77dc98",
                "certification_logo": "view\/static\/svg\/python.svg",
                "duration": "1",
                "level": "Basic",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "5",
                "name": "CSS",
                "description": "CSS: It covers topics like exploring Cascading and Inheritance, exploring text styling fundamentals, understanding the use of layouts in CSS, understand the boxing of elements in CSS, among others.",
                "certification_date": "2021-07-28",
                "certification_url": "https:\/\/www.hackerrank.com\/certificates\/62b3d263cda5",
                "certification_logo": "view\/static\/svg\/css.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "6",
                "name": "JavaScript (Intermediate)",
                "description": "JavaScript (Intermediate): It covers topics like Design Patterns, Memory management, concurrency model, and event loops, among others.",
                "certification_date": "2022-02-15",
                "certification_url": "https:\/\/www.hackerrank.com\/certificates\/ed1793e0e97a",
                "certification_logo": "view\/static\/svg\/js.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "achievement_id": "7",
                "name": "Git",
                "description": "Efficiently manage Git projects, ensuring collaboration, version control, and seamless workflow for enhanced productivity.",
                "certification_date": "2022-02-21",
                "certification_url": "https:\/\/github.com\/FzArnob?tab=achievements",
                "certification_logo": "view\/static\/svg\/git.svg",
                "duration": "1",
                "level": "Intermediate",
                "created_date": "2023-06-26 15:29:13",
                "updated_date": "2023-06-26 00:14:18",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "projects": [
            {
                "project_id": "1",
                "name": "Pocketalk Console \/ Backend Engineer",
                "type": "Enterprise",
                "stack": "Java Spring Boot",
                "details": "Pocketalk is translation device and Console is a new administration panel that allows for fleet management and confirmation of intended use for major business users.",
                "live_url": "https:\/\/bjitgroup.com\/software-development-case-studies\/pocketalk",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53020376333_2b5719fc2e.jpg",
                "duration": "1",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1KNuuqWz09Le1deRa1u68WGF5RbSnvQua",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1H4NNhZ5oy1Zsyw46HIgKgDzqsViuv-V4",
                "additional_image_3": "https:\/\/drive.google.com\/uc?export=view&id=1x6nK6sp3nq-D3e1krNo7zfRHmOxjOmV_",
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "2",
                "name": "Tribel \/ Full Stack",
                "type": "Cross",
                "stack": "React & Node",
                "details": "Tribel is the SMARTER social network where your posts immediately reach the right audience, you finally get the recognition you deserve for making great posts.",
                "live_url": "https:\/\/www.tribel.com\/",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53020285535_915ef0dc8d.jpg",
                "duration": "1",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1KNuuqWz09Le1deRa1u68WGF5RbSnvQua",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1H4NNhZ5oy1Zsyw46HIgKgDzqsViuv-V4",
                "additional_image_3": "https:\/\/drive.google.com\/uc?export=view&id=1x6nK6sp3nq-D3e1krNo7zfRHmOxjOmV_",
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "3",
                "name": "Moviease \/ Developer",
                "type": "Cross",
                "stack": "React Native",
                "details": "Moviease is a platform for online movie and TV show streaming. Students can create an account to participate in exams, where scores are recorded to prevent cheating. It is a cross-platform app under development science January 2022.",
                "live_url": "https:\/\/fzs-lab.com\/Moviease\/",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53011645857_38cec70212.jpg",
                "duration": "1",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1KNuuqWz09Le1deRa1u68WGF5RbSnvQua",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1H4NNhZ5oy1Zsyw46HIgKgDzqsViuv-V4",
                "additional_image_3": "https:\/\/drive.google.com\/uc?export=view&id=1x6nK6sp3nq-D3e1krNo7zfRHmOxjOmV_",
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "4",
                "name": "Simba Chatbot \/ Developer",
                "type": "Machine Learning",
                "stack": "Python",
                "details": "Simba Chatbot is an automated response generating chatbot developed using the DialoGPT-large model. It interacts like a human and involves refining and preprocessing custom datasets. The project has been active since December 2021 for a duration of 2 months.",
                "live_url": null,
                "demo_url": "https:\/\/github.com\/FzArnob\/Chatbot-Simba",
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53012612530_3747ce77e1.jpg",
                "duration": "2",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1W6A_W5DwVDd5W2BLc71XzvpfeY764uRS",
                "additional_image_2": null,
                "additional_image_3": null,
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "5",
                "name": "NinjaHopper \/ Developer",
                "type": "Web",
                "stack": "JavaScript",
                "details": "NinjaHopper is a simple and fun 2D arcade game suitable for both kids and adults. The game is built using HTML, CSS, JavaScript, and 2D SVG images. A future version is planned to include a multiplayer mode. Development of NinjaHopper took place in June 2021 over a duration of 1 month.",
                "live_url": "https:\/\/fzs-lab.com\/NinjaHopper\/",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53012233046_5d91731867.jpg",
                "duration": "1",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1_PTfDoBEHdu8y98lEWSYtlBx_BRc55ef",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1kfSq8xkbCOSYi4-Bu7Rc94He4nkDqDpj",
                "additional_image_3": null,
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "6",
                "name": "CovidEase \/ Team Leader",
                "type": "Mobile",
                "stack": "React Native",
                "details": "CovidEase is a mobile app developed as part of the ICT Innovation Fest. It provides Corona Virus related service information to the people of Bangladesh, collecting and presenting data from private and government health service institutions. The project utilizes Java Script, React, Firebase Real-Time Database, React Animation Add-ons, and Google Maps API. It was developed over a period of 2 months starting from June 2020.",
                "live_url": null,
                "demo_url": "https:\/\/www.youtube.com\/watch?v=eRuBO6WmqV4",
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53012710548_c1b97d9f48.jpg",
                "duration": "2",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1NsCr0yluaM8v1cRbuLRnOcGMmqpdB8-Z",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1pT8j25YT7jIoCOQ474JGZUbjFDCdcdnB",
                "additional_image_3": null,
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "7",
                "name": "Examiner \/ Developer",
                "type": "Web",
                "stack": "PHP",
                "details": "Examiner is a real-time virtual platform for taking MCQ-based exams. It is designed for ease of use by both teachers and students. The project, developed using PHP, CSS, HTML, and JavaScript, follows the MVC pattern and incorporates object-oriented programming principles. Features include account creation, submission of answers, automated completion, live score assessment, and more. Development spanned 3 months, starting from September 2020.",
                "live_url": "https:\/\/fzs-lab.com\/Examiner",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53012612545_7553f6762f.jpg",
                "duration": "3",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1MAAcQfNVrd47__RVlxbFmFLnuHddVtc-",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=1hSDKx2ZbTrK6RgQmKralNkHZSJC_POWC",
                "additional_image_3": "https:\/\/drive.google.com\/uc?export=view&id=1gL-TsOFhWO4AB-34xUkI3WaIw5I9x2rD",
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "project_id": "8",
                "name": "QR Queen \/ Developer",
                "type": "Mobile",
                "stack": "Kodular",
                "details": "QR Queen is a versatile app for creating QR codes with customizable colors and sizes. It allows saving results in various image formats, including vector art formats. The app records all scanned codes and offers scan history. Other features include code encryption, sharing, barcode conversion, and offline scan storage. QR Queen is a mobile app developed over a month, starting from May 2020.",
                "live_url": "https:\/\/play.google.com\/store\/apps\/details?id=com.sunny.qr",
                "demo_url": null,
                "logo_image": "https:\/\/live.staticflickr.com\/65535\/53012396049_ce14507917.jpg",
                "duration": "1",
                "additional_image_1": "https:\/\/drive.google.com\/uc?export=view&id=1zmu8elNALUGMcYZWIOEJ3EUT7SlG7llL",
                "additional_image_2": "https:\/\/drive.google.com\/uc?export=view&id=17HJa1we3_E0QGEUyQXz03OH2tXO9fw2o",
                "additional_image_3": "https:\/\/drive.google.com\/uc?export=view&id=1n9LrciBVdCf_aEpFcT-A8ybBW7qpTrTG",
                "additional_image_4": null,
                "additional_image_5": null,
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "gallery": [
            {
                "gallery_item_id": "1",
                "name": "Sunset between the hills",
                "description": "A breathtaking view of the sunset amidst the hills.",
                "category": "Digital Arts",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008240645_415d39e51a_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008240645_9158c57f5a_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "2",
                "name": "Bodhu",
                "description": "A beautiful oil painting depicting a serene scene.",
                "category": "Oil Paint",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008298725_e566d5d2bd_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008298725_55f592dc2b_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "3",
                "name": "Reflection",
                "description": "A mesmerizing photograph capturing the reflection in still water.",
                "category": "Photography",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53007845157_4f9c0e5b07_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53007845157_087c478dfe_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "4",
                "name": "Kumira Beach",
                "description": "A stunning photograph showcasing the beauty of Kumira Beach.",
                "category": "Photography",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008602744_b8fc8345d2_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008602744_2dd7d72b84_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "5",
                "name": "Oh deer",
                "description": "A digital artwork featuring a majestic deer.",
                "category": "Digital Arts",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53007855741_a3824f5385_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53007855741_9a20ae7d07_c.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "6",
                "name": "Womens Day",
                "description": "A captivating poster design celebrating Womens Day.",
                "category": "Poster",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53007855606_7531027907_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53007855606_2a5fba0a92_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "7",
                "name": "BTF Blood Camp",
                "description": "A poster promoting a blood donation camp organized by BTF.",
                "category": "Poster",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008240370_039e88e8d0_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008240370_22496355a5_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "8",
                "name": "Vegeta - Sketch",
                "description": "A charcoal art sketch depicting the character Vegeta.",
                "category": "Char Coal Art",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008024124_7531027907_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008024124_da44254ede.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "9",
                "name": "Go Green",
                "description": "A social poster advocating for environmental conservation.",
                "category": "Social Poster",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008240395_18c302b598_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008240395_6467dbd81a_z.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "10",
                "name": "Like A Begining",
                "description": "An oil painting capturing the essence of a new beginning.",
                "category": "Oil Paint",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53007262607_ecc6d77e77_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53007262607_0d46100c32_w.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            },
            {
                "gallery_item_id": "11",
                "name": "Bottom Line",
                "description": "A striking photograph with a profound message.",
                "category": "Photography",
                "image_url": "https:\/\/live.staticflickr.com\/65535\/53008414076_7bbb6a96f7_o.jpg",
                "thumb_url": "https:\/\/live.staticflickr.com\/65535\/53008414076_6fbbfa1b05_z.jpg",
                "created_date": "2023-07-30 00:27:44",
                "updated_date": "2023-07-30 00:27:44",
                "delete_flag": "0",
                "fk_profile_id": "farhan"
            }
        ],
        "eca": []
    }
};